### ISSUE TITLE
Uses both GStreamer 0.10 and 1.0

### ISSUE THREAD

**Issue by quozl** [sugarlabs/showntell-activity#3]
`textarea.py` contains both a `gst-launch-0.10` command line and uses GStreamer 1.0 in rest of code; it should be ported to use GStreamer 1.0 entirely.

**Comment by quozl** [comment]
With 98bb4f0, contains use of `gst-launch-0.10` and imports GStreamer 1.0 without using it.  Still needs porting to GStreamer 1.0.

**Comment by chimosky** [comment]
Fixed #6.
